server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka,
      # 集群
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: order8080
    prefer-ip-address: true


spring:
  application:
    name: cloud-order-service

#    // 无法同时使用两个 注册中心 会报错
#    // Field registration in org.springframework.cloud.client.serviceregistry
#    // .ServiceRegistryAutoConfiguration$ServiceRegistryEndpointConfiguration required a single bean, but 2 were found:
#    //	- eurekaRegistration: defined in BeanDefinition defined in class path resource
#    //	[org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration$RefreshableEurekaClientConfiguration
#    //	.class]
#    //	- consulRegistration: defined by method 'consulRegistration' in class path resource
#    //	[org/springframework/cloud/consul/serviceregistry/ConsulAutoServiceRegistrationAutoConfiguration.class]
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}